# Generated by Django 6.0.5 on 2026-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0002_specialty_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
