# Generated by Django 6.0.5 on 2026-05-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0003_rider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('race_type', models.CharField(choices=[('GT', 'Grand Tour'), ('MON', 'Monument'), ('OW', 'One Week Race')], max_length=10)),
                ('total_stages', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=6)),
                ('stage_type', models.CharField(choices=[('FL', 'Flat'), ('HI', 'Hilly'), ('MT', 'Mountain'), ('IT', 'Individual Time Trial'), ('TT', 'Team Time Trial')], max_length=10)),
                ('stage_status', models.CharField(choices=[('NR', 'Normal'), ('CA', 'Cancelled'), ('SH', 'Shortened')], default='NR', max_length=10)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='peloton.race')),
            ],
            options={
                'ordering': ['race', 'stage_number'],
            },
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_position', models.IntegerField(blank=True, null=True)),
                ('finish_status', models.CharField(choices=[('FIN', 'Finished'), ('DNF', 'Did not Finish'), ('DNS', 'Did not Start'), ('DSQ', 'Disqualified')], default='FIN', max_length=10)),
                ('time_in_seconds', models.IntegerField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='peloton.rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='peloton.stage')),
            ],
            options={
                'ordering': ['stage', 'finishing_position'],
                'unique_together': {('stage', 'rider')},
            },
        ),
    ]
