# Generated by Django 6.0.5 on 2026-05-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0004_race_stage_stageresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='has_cobbles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='has_steep_climbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='terrain_type',
            field=models.CharField(blank=True, choices=[('FL', 'Flat'), ('HI', 'Hilly'), ('MT', 'Mountain')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stageresult',
            name='finish_status',
            field=models.CharField(choices=[('FIN', 'Finished'), ('DNF', 'Did Not Finish'), ('DNS', 'Did Not Start'), ('DSQ', 'Disqualified')], default='FIN', max_length=10),
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_position', models.IntegerField(blank=True, null=True)),
                ('finish_status', models.CharField(choices=[('FIN', 'Finished'), ('DNF', 'Did Not Finish'), ('DNS', 'Did Not Start'), ('DSQ', 'Disqualified')], default='FIN', max_length=10)),
                ('time_in_seconds', models.IntegerField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='peloton.race')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='peloton.rider')),
            ],
            options={
                'ordering': ['race', 'finishing_position'],
                'unique_together': {('race', 'rider')},
            },
        ),
    ]
