# Generated by Django 6.0.5 on 2026-05-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0005_race_distance_km_race_has_cobbles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='grand_tour_name',
            field=models.CharField(blank=True, choices=[('TDF', 'Tour de France'), ('GIR', "Giro d'Italia"), ('VUE', 'La Vuelta')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='monument_name',
            field=models.CharField(blank=True, choices=[('PR', 'Paris-Roubaix'), ('RVV', 'Ronde van Vlaanderen'), ('LBL', 'Liège-Bastogne-Liège'), ('MSR', 'Milan-San Remo'), ('LOM', 'Il Lombardia')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='finish_status',
            field=models.CharField(choices=[('FIN', 'Finished'), ('DNF', 'Did Not Finished'), ('DNS', 'Did Not Start'), ('DSQ', 'Disqualified')], default='FIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='stageresult',
            name='finish_status',
            field=models.CharField(choices=[('FIN', 'Finished'), ('DNF', 'Did Not Finished'), ('DNS', 'Did Not Start'), ('DSQ', 'Disqualified')], default='FIN', max_length=10),
        ),
    ]
