# Generated by Django 6.0.5 on 2026-05-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0006_race_grand_tour_name_race_monument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
