# Generated by Django 6.0.5 on 2026-06-01 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0007_alter_race_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.IntegerField(default=0)),
                ('climbing', models.IntegerField(default=0)),
                ('hills', models.IntegerField(default=0)),
                ('one_day_races', models.IntegerField(default=0)),
                ('time_trial', models.IntegerField(default=0)),
                ('ftp', models.IntegerField(blank=True, null=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='peloton.rider')),
            ],
        ),
    ]
