# Generated by Django 6.0.5 on 2026-06-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0008_riderprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain_type', models.CharField(choices=[('FL', 'Flat'), ('HI', 'Hilly'), ('MT', 'Mountain'), ('TT', 'Time Trial')], max_length=10, unique=True)),
                ('base_speed_kmh', models.FloatField()),
                ('seconds_per_score_point', models.IntegerField(default=4)),
                ('endurance_weight', models.FloatField(default=0.3)),
                ('cobble_weight', models.FloatField(default=0.3)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='race_style',
            field=models.CharField(choices=[('bunch_sprint', 'Bunch Sprint'), ('breakaway', 'Solo Breakaway'), ('gc_battle', 'GC Battle')], default='breakaway', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='weather',
            field=models.CharField(choices=[('dry', 'Dry'), ('rain', 'Rain'), ('wind', 'Wind'), ('heat', 'Heat'), ('cold', 'Cold')], default='dry', max_length=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='cobbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='endurance',
            field=models.IntegerField(default=70),
        ),
    ]
