# Generated by Django 6.0.5 on 2026-06-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peloton', '0009_simulationconfig_race_race_style_race_weather_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nationality',
            new_name='country',
        ),
    ]
